apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weatherserviceweb2
  labels:
    app: weatherserviceweb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherserviceweb2
  template:
    metadata:
      labels:
        app: weatherserviceweb2
    spec:
      containers:
      - name: weatherserviceweb2
        image: us.gcr.io/weatherservice-195512/weatherserviceweb
        ports:
        - containerPort: 8088
