---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: web-weather
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: weatherserviceweb
           image: us.gcr.io/weatherservice-195512/weatherserviceweb
           ports:
             - containerPort: 8080
