---
 apiVersion: v1
 kind: Pod
 metadata:
   name: web-weather-service
   labels:
     app: web
 spec:
   containers:
     - name: weatherserviceweb
       image: us.gcr.io/weatherservice-195512/weatherserviceweb
       ports:
         - containerPort: 8080
